// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blob.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type APIKeyBlob struct {
	Algorithm            string   `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Secret               []byte   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	ECDSAKey             []byte   `protobuf:"bytes,3,opt,name=ECDSA_key,json=ECDSAKey,proto3" json:"ECDSA_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIKeyBlob) Reset()         { *m = APIKeyBlob{} }
func (m *APIKeyBlob) String() string { return proto.CompactTextString(m) }
func (*APIKeyBlob) ProtoMessage()    {}
func (*APIKeyBlob) Descriptor() ([]byte, []int) {
	return fileDescriptor_6903d1e8a20272e8, []int{0}
}

func (m *APIKeyBlob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIKeyBlob.Unmarshal(m, b)
}
func (m *APIKeyBlob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIKeyBlob.Marshal(b, m, deterministic)
}
func (m *APIKeyBlob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIKeyBlob.Merge(m, src)
}
func (m *APIKeyBlob) XXX_Size() int {
	return xxx_messageInfo_APIKeyBlob.Size(m)
}
func (m *APIKeyBlob) XXX_DiscardUnknown() {
	xxx_messageInfo_APIKeyBlob.DiscardUnknown(m)
}

var xxx_messageInfo_APIKeyBlob proto.InternalMessageInfo

func (m *APIKeyBlob) GetAlgorithm() string {
	if m != nil {
		return m.Algorithm
	}
	return ""
}

func (m *APIKeyBlob) GetSecret() []byte {
	if m != nil {
		return m.Secret
	}
	return nil
}

func (m *APIKeyBlob) GetECDSAKey() []byte {
	if m != nil {
		return m.ECDSAKey
	}
	return nil
}

func init() {
	proto.RegisterType((*APIKeyBlob)(nil), "auth.APIKeyBlob")
}

func init() { proto.RegisterFile("blob.proto", fileDescriptor_6903d1e8a20272e8) }

var fileDescriptor_6903d1e8a20272e8 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xca, 0xc9, 0x4f,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2c, 0x2d, 0xc9, 0x50, 0x8a, 0xe7, 0xe2,
	0x72, 0x0c, 0xf0, 0xf4, 0x4e, 0xad, 0x74, 0xca, 0xc9, 0x4f, 0x12, 0x92, 0xe1, 0xe2, 0x4c, 0xcc,
	0x49, 0xcf, 0x2f, 0xca, 0x2c, 0xc9, 0xc8, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x42, 0x08,
	0x08, 0x89, 0x71, 0xb1, 0x15, 0xa7, 0x26, 0x17, 0xa5, 0x96, 0x48, 0x30, 0x29, 0x30, 0x6a, 0xf0,
	0x04, 0x41, 0x79, 0x42, 0xd2, 0x5c, 0x9c, 0xae, 0xce, 0x2e, 0xc1, 0x8e, 0xf1, 0xd9, 0xa9, 0x95,
	0x12, 0xcc, 0x60, 0x29, 0x0e, 0xb0, 0x80, 0x77, 0x6a, 0x65, 0x12, 0x1b, 0xd8, 0x36, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xca, 0xa1, 0x9d, 0x7b, 0x00, 0x00, 0x00,
}
